### ISSUE TITLE
[Bug] Different hash during postman request

### ISSUE THREAD

**Issue by hookenful** [DrBarnabus/Servly#11] opened 2022-05-12 12:12 UTC
Hello there!

I am trying to implement idempotency middleware and during testing the same request (with same parameters), I am having an error about: "A request with a different hash attempted to utilize the same idempotency key of {IdempotencyKey}". 

How to check the idempotency thing with postman without that error?

Thanks in advance

**Comment by hookenful** [comment] 2022-05-12 12:49
The problem was in  `context.Request.EnableBuffering();` . I've removed it and became fine, does it mandatory? Why do we need that?

**Comment by hookenful** [comment] 2022-05-15 07:24
![image](https://user-images.githubusercontent.com/31849464/168461957-4212b4cc-6f7e-4299-bcab-9deee367d7b1.png)

Seems System.Text.Json can't consume the request body stream anymore since you've already consumed it in your middleware. Is it possible to fix ?

**Comment by DrBarnabus** [comment] 2022-07-28 21:31
@hookenful Sorry for the delay in seeing this issue, I've been away from this project for a while.

> I am trying to implement idempotency middleware and during testing the same request (with same parameters), I am having an error about: "A request with a different hash attempted to utilize the same idempotency key of {IdempotencyKey}".
> 
> How to check the idempotency thing with postman without that error?

That error would be caused by a different request sharing an Idempotency Key that has already been used within the timeframe  of it being kept in Redis. Each unique request needs a different idempotency key the error was left as a warning that different requests could be unintentionally being sent with different keys.

> Seems System.Text.Json can't consume the request body stream anymore since you've already consumed it in your middleware. Is it possible to fix?

That exception doesn't look to be from the code in this repository so I am going to close this issue off. If you are still having issues with this package please open a new issue but bear in mind this set of packages is still heavily in development and is provided as is.

**Closed as not planned by DrBarnabus** 2022-07-28 21:31 UTC
